version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: warah/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: warah/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: nginx:1.19.3
    ports:
      - "7777:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media